_target_: src.losses.finetune_loss.FinetuneLoss
bce_weight: 0.5
dice_weight: 0.5
lam_vol: 0.1
lam_ef: 0.75
lam_phase: 0.1
lam_curv: 0.005
lam_phase_smooth: 0.01
lam_l1: 0.00001
lam_prior: 0.0005
log_c_init: -6.907755
