train:
  _target_: src.datasets.echonet.EchoNetDataset
  root_dir: /workspace/data/EchoNet-Dynamic
  split: train
  img_size: [112, 112]

val:
  _target_: src.datasets.echonet.EchoNetDataset
  root_dir: /workspace/data/EchoNet-Dynamic
  split: val
  img_size: [112, 112]

test:
  _target_: src.datasets.echonet.EchoNetDataset
  root_dir: /workspace/data/EchoNet-Dynamic
  split: test
  img_size: [112, 112]

num_workers: 12
batch_size: 4
