optimizer:
  _target_: torch.optim.SGD
  lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4

frozen_module_names: null

amp:
  enabled: true
  amp_dtype: float16

gradient_clip:
  _target_: src.utils.gradient_clip.GradientClipper
  configs: []

options:
  lr:
    - scheduler:
        _target_: fvcore.common.param_scheduler.CompositeParamScheduler
        schedulers:
          - _target_: fvcore.common.param_scheduler.LinearParamScheduler
            start_value: 1e-6
            end_value: 0.01
          - _target_: fvcore.common.param_scheduler.CosineParamScheduler
            start_value: 0.01
            end_value: 1e-6
        lengths: [0.05, 0.95]
        interval_scaling: ["rescaled", "rescaled"]
